// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JsonLib
{

    internal class Calibration
    {

        [JsonProperty("SensorCalibration")]
        public SensorCalibration[] SensorCalibration { get; set; }
    }

}
