// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JsonLib
{

    internal class SensorCalibration
    {

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Zero")]
        public double Zero { get; set; }

        [JsonProperty("Span")]
        public double Span { get; set; }

        [JsonProperty("Min")]
        public double Min { get; set; }

        [JsonProperty("Max")]
        public double Max { get; set; }
    }

}
